# Constants
INITIAL_SCREEN_WIDTH = 800
INITIAL_SCREEN_HEIGHT = 600
FRICTION_COEFFICIENT = 0.8
INITIAL_GROUND_LEVEL = INITIAL_SCREEN_HEIGHT * 0.65
FPS = 60  # Target frame rate
GRAVITY = 9.8 / FPS
JUMP_STRENGTH = 120 / FPS
FOLLOW_POINT_RETURN_INTERVAL = 2 * FPS
TILE_SIZE = 16